package com.filmstore.model;
// Generated 19-Jan-2016 04:42:30 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Movie generated by hbm2java
 */
public class Movie  implements java.io.Serializable {


     private Integer id;
     private Date timestamp;
     private String title;
     private String description;
     private String releasedate;
     private int price;
     private int numberOfMovies;
     private Double feedback;
     private String duration;

    public Movie() {
    }

	
    public Movie(String title, String description, String releasedate, int price, int numberOfMovies, String duration) {
        this.title = title;
        this.description = description;
        this.releasedate = releasedate;
        this.price = price;
        this.numberOfMovies = numberOfMovies;
        this.duration = duration;
    }
    public Movie(String title, String description, String releasedate, int price, int numberOfMovies, Double feedback, String duration) {
       this.title = title;
       this.description = description;
       this.releasedate = releasedate;
       this.price = price;
       this.numberOfMovies = numberOfMovies;
       this.feedback = feedback;
       this.duration = duration;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getReleasedate() {
        return this.releasedate;
    }
    
    public void setReleasedate(String releasedate) {
        this.releasedate = releasedate;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    public int getNumberOfMovies() {
        return this.numberOfMovies;
    }
    
    public void setNumberOfMovies(int numberOfMovies) {
        this.numberOfMovies = numberOfMovies;
    }
    public Double getFeedback() {
        return this.feedback;
    }
    
    public void setFeedback(Double feedback) {
        this.feedback = feedback;
    }
    public String getDuration() {
        return this.duration;
    }
    
    public void setDuration(String duration) {
        this.duration = duration;
    }




}


