package com.filmstore.model;
// Generated 19-Jan-2016 04:42:30 by Hibernate Tools 4.3.1



/**
 * Purchase generated by hbm2java
 */
public class Purchase  implements java.io.Serializable {


     private Integer purchaseid;
     private int id;
     private String email;
     private String status;

    public Purchase() {
    }

    public Purchase(int id, String email, String status) {
       this.id = id;
       this.email = email;
       this.status = status;
    }
   
    public Integer getPurchaseid() {
        return this.purchaseid;
    }
    
    public void setPurchaseid(Integer purchaseid) {
        this.purchaseid = purchaseid;
    }
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


